/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesse Benjamin Cerbo
 */
public class TeacherUserForm extends javax.swing.JFrame {

    /**
     * Creates new form TeacherUserForm
     */
    public TeacherUserForm() {
        initComponents();
        
        // Show the Class List of the Logged-in Teacher
        showTeacherClassList();
        
        // Add an event handler for when the Teacher's Class List selection has changed
        jTableClassList.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                int selected_row_index = jTableClassList.getSelectedRow();
                System.out.println("jTableClassList selected: " + selected_row_index);
                if(selected_row_index !=-1) {
                    EnrollmentSystem.selected_subject_ID = String.valueOf(jTableClassList.getValueAt(selected_row_index, 0));
                    showClassGradesList();
                }
                else {
                    EnrollmentSystem.selected_subject_ID = "";
                    clearClassGradesList();
                }
            }
        });
        
        // Add an event handler for when the Class' Grade List selection has changed
        jTableClassGrades.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                int selected_row_index = jTableClassGrades.getSelectedRow();
                System.out.println("jTableClassGrades selected: " + selected_row_index);
                if(selected_row_index !=-1) {
                    EnrollmentSystem.selected_student_ID = String.valueOf(jTableClassGrades.getValueAt(selected_row_index, 0));
                    showClassGradeForm(selected_row_index);
                }
                else {  //deselect row
                    EnrollmentSystem.selected_student_ID = "";
                    clearClassGradeForm();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableClassList = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldStudentID = new javax.swing.JTextField();
        jTextFieldStudentName = new javax.swing.JTextField();
        jComboBoxGradePrelim = new javax.swing.JComboBox<>();
        jComboBoxGradeMidTerm = new javax.swing.JComboBox<>();
        jComboBoxGradePreFinal = new javax.swing.JComboBox<>();
        jComboBoxGradeFinal = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClassGrades = new javax.swing.JTable();
        jButtonSaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teachers Class List / Grades Encoding Form");

        jTableClassList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Code", "Description", "Units", "Schedule", "Students"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClassList.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableClassList);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Student ID");
        jLabel8.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel8.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Student Name");
        jLabel9.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Prelim");
        jLabel10.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Mid-Term");
        jLabel11.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Pre-Final");
        jLabel12.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel12.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Final");
        jLabel13.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(80, 25));

        jTextFieldStudentID.setEditable(false);
        jTextFieldStudentID.setMaximumSize(new java.awt.Dimension(80, 25));
        jTextFieldStudentID.setMinimumSize(new java.awt.Dimension(80, 25));
        jTextFieldStudentID.setName(""); // NOI18N
        jTextFieldStudentID.setPreferredSize(new java.awt.Dimension(80, 25));

        jTextFieldStudentName.setEditable(false);
        jTextFieldStudentName.setMaximumSize(new java.awt.Dimension(80, 25));
        jTextFieldStudentName.setMinimumSize(new java.awt.Dimension(80, 25));
        jTextFieldStudentName.setName(""); // NOI18N
        jTextFieldStudentName.setPreferredSize(new java.awt.Dimension(80, 25));

        jComboBoxGradePrelim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        jComboBoxGradePrelim.setSelectedIndex(-1);
        jComboBoxGradePrelim.setMaximumSize(new java.awt.Dimension(80, 25));
        jComboBoxGradePrelim.setMinimumSize(new java.awt.Dimension(80, 25));
        jComboBoxGradePrelim.setPreferredSize(new java.awt.Dimension(80, 25));

        jComboBoxGradeMidTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        jComboBoxGradeMidTerm.setSelectedIndex(-1);
        jComboBoxGradeMidTerm.setMaximumSize(new java.awt.Dimension(80, 25));
        jComboBoxGradeMidTerm.setMinimumSize(new java.awt.Dimension(80, 25));
        jComboBoxGradeMidTerm.setPreferredSize(new java.awt.Dimension(80, 25));

        jComboBoxGradePreFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        jComboBoxGradePreFinal.setSelectedIndex(-1);
        jComboBoxGradePreFinal.setMaximumSize(new java.awt.Dimension(80, 25));
        jComboBoxGradePreFinal.setMinimumSize(new java.awt.Dimension(80, 25));
        jComboBoxGradePreFinal.setPreferredSize(new java.awt.Dimension(80, 25));

        jComboBoxGradeFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        jComboBoxGradeFinal.setSelectedIndex(-1);
        jComboBoxGradeFinal.setMaximumSize(new java.awt.Dimension(80, 25));
        jComboBoxGradeFinal.setMinimumSize(new java.awt.Dimension(80, 25));
        jComboBoxGradeFinal.setPreferredSize(new java.awt.Dimension(80, 25));

        jTableClassGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Prelim", "Mid-Term", "Pre-Final", "Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClassGrades.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableClassGrades);

        jButtonSaveButton.setText("Save");
        jButtonSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGradePrelim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGradeMidTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGradePreFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGradeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSaveButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGradePrelim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGradeMidTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGradePreFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGradeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveButtonActionPerformed
        saveClassGradeForm();
    }//GEN-LAST:event_jButtonSaveButtonActionPerformed

    /**
     * Show the Class List of the Logged-in Teacher
     */
    private void showTeacherClassList() {    
        DBConnect connect = new DBConnect();

        try {
            // Get the teacherID from the current logged-in username
            teachers teachers = new teachers();
            teachers.getLoggedInTeacherId();
            
            // Fill-in the teacher's class list
            DefaultTableModel tblmodel = (DefaultTableModel) jTableClassList.getModel();
            tblmodel.setRowCount(0);
            String getTeacherClassListQuery = "SELECT * FROM (SELECT assign.teacherID, class_tbl.* FROM assign LEFT JOIN (SELECT subjects.*, COALESCE(student_count, 0) AS student_count FROM subjects LEFT JOIN (SELECT subjectID, count(studentID) AS student_count FROM enroll GROUP BY subjectID) AS student_count_tbl ON subjects.subjectID = student_count_tbl.subjectID ) class_tbl ON assign.subjectID = class_tbl.subjectID) AS class_tbl WHERE teacherID = " + EnrollmentSystem.logged_in_teacherID;
            System.out.println(getTeacherClassListQuery);
            connect.rs = connect.st.executeQuery(getTeacherClassListQuery);
            System.out.println("Query Success!");
            while (connect.rs.next()) {
                String id           = connect.rs.getString("subjectID");
                String code         = connect.rs.getString("subjectCODE");
                String description  = connect.rs.getString("subjectDESCRIPTION");
                String units        = connect.rs.getString("subjectUNITS");
                String schedule     = connect.rs.getString("subjectSCHEDULE");
                String studentCount = connect.rs.getString("student_count");
                Object[] item = { id, code, description, units, schedule, studentCount };
                tblmodel.addRow(item);
            }
        }
        catch(Exception ex){
            System.out.println("Failed: " + ex);
        }
    }
    
    public void showClassGradesList(){
        try {
            DefaultTableModel tblmodel = (DefaultTableModel) jTableClassGrades.getModel();
            tblmodel.setRowCount(0);
            DBConnect connect2 = new DBConnect();
            String query2 = "SELECT * FROM (SELECT enroll.enrollID, enroll.subjectID, enroll.studentID, students.studentName, grades.Prelim, grades.Midterm, grades.Prefinal, grades.Final FROM enroll LEFT JOIN students ON enroll.studentID = students.studentID LEFT JOIN grades ON enroll.enrollID = grades.enrollID) AS class_grades_tbl WHERE subjectID = " + EnrollmentSystem.selected_subject_ID;
            connect2.rs = connect2.st.executeQuery(query2);
            System.out.println("Query Success!");
            while (connect2.rs.next()) {
                String id       = connect2.rs.getString("studentID");
                String name     = connect2.rs.getString("studentName");
                String Prelim   = connect2.rs.getString("Prelim");
                String Midterm  = connect2.rs.getString("Midterm");
                String Prefinal = connect2.rs.getString("Prefinal");
                String Final    = connect2.rs.getString("Final");
                Object[] item = {id, name, Prelim, Midterm, Prefinal, Final};
                tblmodel.addRow(item);
            }
        }
        catch(Exception ex){
            System.out.println("Failed: " + ex);
        }
    }
    
    public void clearClassGradesList(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTableClassGrades.getModel();
        tblmodel.setRowCount(0);
    }
    
    public void showClassGradeForm(int selectedRow){
        clearClassGradeForm();
        jTextFieldStudentID.setText(EnrollmentSystem.selected_student_ID);
        jTextFieldStudentName.setText(String.valueOf(jTableClassGrades.getValueAt(selectedRow, 1)));
        jComboBoxGradePrelim.setSelectedItem(String.valueOf(jTableClassGrades.getValueAt(selectedRow, 2)));
        jComboBoxGradeMidTerm.setSelectedItem(String.valueOf(jTableClassGrades.getValueAt(selectedRow, 3)));
        jComboBoxGradePreFinal.setSelectedItem(String.valueOf(jTableClassGrades.getValueAt(selectedRow, 4)));
        jComboBoxGradeFinal.setSelectedItem(String.valueOf(jTableClassGrades.getValueAt(selectedRow, 5)));
    }
    
    public void clearClassGradeForm(){
        jTextFieldStudentID.setText("");
        jTextFieldStudentName.setText("");
        jComboBoxGradePrelim.setSelectedIndex(-1);
        jComboBoxGradeMidTerm.setSelectedIndex(-1);
        jComboBoxGradePreFinal.setSelectedIndex(-1);
        jComboBoxGradeFinal.setSelectedIndex(-1);
    }
    
    public void saveClassGradeForm(){
        int studentID = Integer.parseInt(EnrollmentSystem.selected_student_ID);
        int subjectID = Integer.parseInt(EnrollmentSystem.selected_subject_ID);
        String prelimGrade = "";
        String midTermGrade = "";
        String preFinalGrade = "";
        String finalGrade = "";
        
        if(jComboBoxGradePrelim.getSelectedIndex() >= 0){ prelimGrade = String.valueOf(jComboBoxGradePrelim.getSelectedItem()); }
        if(jComboBoxGradeMidTerm.getSelectedIndex() >= 0){ midTermGrade = String.valueOf(jComboBoxGradeMidTerm.getSelectedItem()); }
        if(jComboBoxGradePreFinal.getSelectedIndex() >= 0){ preFinalGrade = String.valueOf(jComboBoxGradePreFinal.getSelectedItem()); }
        if(jComboBoxGradeFinal.getSelectedIndex() >= 0){ finalGrade = String.valueOf(jComboBoxGradeFinal.getSelectedItem()); }
        
        Grades grades = new Grades();
        grades.update_grades(studentID, subjectID, prelimGrade, midTermGrade, preFinalGrade, finalGrade);

        showClassGradesList();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveButton;
    private javax.swing.JComboBox<String> jComboBoxGradeFinal;
    private javax.swing.JComboBox<String> jComboBoxGradeMidTerm;
    private javax.swing.JComboBox<String> jComboBoxGradePreFinal;
    private javax.swing.JComboBox<String> jComboBoxGradePrelim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableClassGrades;
    private javax.swing.JTable jTableClassList;
    private javax.swing.JTextField jTextFieldStudentID;
    private javax.swing.JTextField jTextFieldStudentName;
    // End of variables declaration//GEN-END:variables
}
